// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMzmY75a9aa0RoNNJ-BKBY-ztAEZVnAeM',
    appId: '1:564439323645:web:062f00d1a4b82ecaa4ff94',
    messagingSenderId: '564439323645',
    projectId: 'milkbiz-flutter',
    authDomain: 'milkbiz-flutter.firebaseapp.com',
    storageBucket: 'milkbiz-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMSZ0dk9b4YNCFVxkQ4uW9cIrzjS5q5sY',
    appId: '1:564439323645:android:e925552a51ae25daa4ff94',
    messagingSenderId: '564439323645',
    projectId: 'milkbiz-flutter',
    storageBucket: 'milkbiz-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZADVLYlA2dotsuyl59JoJpg9tYVYsI2E',
    appId: '1:564439323645:ios:c6cea8e1983ff098a4ff94',
    messagingSenderId: '564439323645',
    projectId: 'milkbiz-flutter',
    storageBucket: 'milkbiz-flutter.firebasestorage.app',
    iosBundleId: 'com.example.milkbiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZADVLYlA2dotsuyl59JoJpg9tYVYsI2E',
    appId: '1:564439323645:ios:c6cea8e1983ff098a4ff94',
    messagingSenderId: '564439323645',
    projectId: 'milkbiz-flutter',
    storageBucket: 'milkbiz-flutter.firebasestorage.app',
    iosBundleId: 'com.example.milkbiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMzmY75a9aa0RoNNJ-BKBY-ztAEZVnAeM',
    appId: '1:564439323645:web:24ce933748976e60a4ff94',
    messagingSenderId: '564439323645',
    projectId: 'milkbiz-flutter',
    authDomain: 'milkbiz-flutter.firebaseapp.com',
    storageBucket: 'milkbiz-flutter.firebasestorage.app',
  );
}
